3click:
  prompt: |
    Твоя задача будет найти нужные значения из фрагментов текста и заменить их ориентируясь на списки: список_регионов: {region_list}, список_номенклатуры: {nmn_list}.
    1. Найди в этой строке {msg_head} Регион ориентируясь на список_регионов. Если региона нет из списка, то найди похожее на регион из этой строки. Если похожего нет, то переходи к следующему пункту
    2. Если в предыдущем пункте не нашел региона, то Найди в этой строке {msg_region} регион ориентируясь на список регионов список_регионов. Если региона нет из списка, то найди похожее на регион из этой строки. Если похожего нет, то регион будет None
    3. Найди в этой строке {msg_head} Номенклатуру печати ориентируясь на список_номенклатуры. Если номенклатуры нет из списка, то найди похожее на номенклатуру из этой строки. Если похожего нет, то номенклатура будет None
    4. Найди в этой строке {msg_deadline}. Если даты нет, то Дата будет None
    5. Верни json в виде: {"type_nmn": Номенклатура печати, "deadline": Дата, "region": Регион}
    Верни только json
